name: Auto Update VPN Data

on:
  schedule:
    - cron: '0 3 * * *'  # 每天 UTC+0 3:00（印度早上 8:30）
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # 关闭自动凭据，方便后面手动配置

      - name: Set up Git credentials for pushing
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: |
          python scripts/run_all.py

      - name: Commit and push changes
        run: |
          git add data/*
          CHANGES=$(git diff --cached --name-only)
          if [ -n "$CHANGES" ]; then
            git commit -m "Auto update subscription files [skip ci]"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
